### ISSUE TITLE
No Content-Type header present for POST requests in generated HTML

### ISSUE THREAD

**Issue by stremovsky** [postmanlabs/postman-code-generators#279] opened 2020-06-03 14:39 UTC
**Describe the bug**
Hi, after I publish my API collection, all Content-Type headers are missing in generated HTML, making this HTML document unusable for my users.

You can take look at the resulting HTML here:
https://documenter.getpostman.com/view/11310294/Szmcbz32?version=latest

**To Reproduce**
I just created a number of requests including one that does POST request with: 'Content-Type: application/json'. In the resulting HTL, it is missing.

**Expected code snippet and corresponding request**
The header should be present.

**Additional context**
If you have any reference material which might help us debug the problem please add it here:
Version of postman-code-generators/Postman app: Postman v7.25.2

Thanks

**Comment by webholik** [comment] 2020-10-29 03:43
@stremovsky Content-Type seems to be present now in the generated snipped. For example:
```
PUT /v1/userapp/token/8c8b92b0-58c6-36db-634d-f0b0c798efd8/shipping HTTP/1.1
Host: demo.paranoidguy.com
Content-Type: application/json
X-Bunker-Token: DEMO

{
	"pob": 123
}
```

Could you confirm if this is still an issue?

**Comment by akshaydeo** [comment] 2023-02-06 10:16
@stremovsky closing the ticket as the issue is fixed. Please feel free to open the ticket if you are still facing the issue 🙇‍♂

**Closed by akshaydeo** 2023-02-06 10:16 UTC
Labels: need-more-info, codegen

**Comment by stremovsky** [comment] 2023-02-06 10:40
Hi,

I can conform that it works correctly now for my project ;-)
https://github.com/securitybunker/databunker
