### ISSUE TITLE
[PowerShell] The body parameter of Invoke-RestMethod should be null, not an emtpy string when using Get requests.

### ISSUE THREAD

**Issue by JeromeLefebvre** [postmanlabs/postman-code-generators#146] opened 2019-12-27 04:42 UTC
**Describe the bug**
When doing a Get request, with an empty body and using the "PowerShell - RestMethod" code snippet, an error will be raised as the Invoke-Request method is improperly called.

**To Reproduce**
1. Create a Get request to any ressource, say "example.com". The code generated will be:

```powershell
$body = ""

$response = Invoke-RestMethod 'https://example.com/' -Method 'GET' -Headers $headers -Body $body
$response | ConvertTo-Json
```
The error returned by Powershell is the following:

```powershell
Invoke-RestMethod : コンテンツ本体をこの verb-type では送信できません。
発生場所 行:3 文字:6
+ $a = Invoke-RestMethod 'https://example.com/' -Method 'GET' -Headers  ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], ProtocolViolationException
    + FullyQualifiedErrorId : System.Net.ProtocolViolationException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Expected code snippet and corresponding request**
This snippet instead works:
```powershell
$body = $null

$response = Invoke-RestMethod 'https://example.com/' -Method 'GET' -Headers $headers -Body $body
$response | ConvertTo-Json
```

**Additional context**
Version of postman-code-generators/Postman app: 7.14.0

**Comment by webholik** [comment] 2020-10-23 04:48
@JeromeLefebvre I am not able to reproduce this. The request goes fine for Powershell v7.

**Comment by akshaydeo** [comment] 2023-02-06 08:55
@JeromeLefebvre closing this issue as we couldn't reproduce it. Feel free to re-open if you are still facing this issue 🙇‍♂

**Closed by akshaydeo** 2023-02-06 08:55 UTC
Labels: codegen
