### ISSUE TITLE
Content-Type missing in Python Requests  code generated for file upload of image

### ISSUE THREAD

**Issue by benjose22** [postmanlabs/postman-code-generators#247] opened 2020-05-15 05:37 UTC
**Describe the bug**
Content-Type is mandate while sending POST request for image upload. Content-Type is missing while generating Python Requests code using Postman code generator. E.g. 'image/png' hs to be included for uploading PNG files.

**To Reproduce**
In Body, set form-data.
Set KEY as 'upload' (note that this is not relevernt to the issue. I am just trying to match the screenshot.). Choose File from the dropdown(default is Text)
Set value - choose a png image from you computer.
Genererate Python Requests code.
Try executing the python code. We get error as invalid PNG file.

**Expected code snippet and corresponding request**
Expected-
files = [('upload', ('png_image.png', open('png_image.png', 'rb'), 'image/png'))]
Current - 
files = [
  ('upload', open('/C:/fileupload/png_image.png','rb'))
]

**Screenshots**
![image](https://user-images.githubusercontent.com/56347659/82015289-0ae3fe80-969c-11ea-93c5-64e38e706539.png)

![image](https://user-images.githubusercontent.com/56347659/82015348-2e0eae00-969c-11ea-84e1-d266a3a9c658.png)

**Comment by someshkoli** [comment] 2020-05-17 14:42
Try turning off the new codegen mode in the settings. 
![image](https://user-images.githubusercontent.com/41543649/82151584-ba29fc80-9879-11ea-8356-2f64b1576c46.png)

and try to use that snippet again ? I'm getting diffrent code snippets
This is new codegen mode turned off:

    import requests

    url = "http:///upload"

    payload = "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"upload\"; filename=\"Screenshot from 2020-05-16 19-00-00.png\"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--"
    headers = {
        'content-type': "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW",
        'cache-control': "no-cache",
        'Postman-Token': "b7e7c718-7cbc-4fd4-aca7-657f6ae3aa0c"
        }

    response = requests.request("GET", url, data=payload, headers=headers)

    print(response.text)`

New codegen mode turned on:

        import requests  

        url = "/upload"

        payload = {}
        files = {('upload': open('/home/wolf/Pictures/Screenshot from 2020-05-16 19-00-00.png','rb')}
        headers= {}

        response = requests.request("GET", url, headers=headers, data = payload, files = files)

        print(response.text.encode('utf8'))

**Comment by Marti2203** [comment] 2020-05-17 14:57
Just a quick nitpick as i am just checking out this issue because of a similar problem with the codegenerator for Python Requests. You have generated a GET request and not a POST, I do not think it is a big issue, but just informing as I saw the answer is recent and it would be good to fix it it before it creates more hassles

**Comment by benjose22** [comment] 2020-05-18 02:35
Wow! The old code generator works like a charm!

Do you want me close this issue or you guys are fixing in new code gen?

**Comment by Marti2203** [comment] 2020-05-18 06:39
Currently me and @dasyad00 have made a pull request that may fix the new code generator issue as we also had some problems with it.

**Comment by someshkoli** [comment] 2020-05-18 07:44
> Wow! The old code generator works like a charm!
> 
> Do you want me close this issue or you guys are fixing in new code gen? 

Let it be here. The maintainers will close it.

**Comment by someshkoli** [comment] 2020-05-27 20:16
@benjose22  Can you tell me exactly which request was giving an error ?  I am not able to reproduce it now ?

**Closed** 2020-10-29 13:44 UTC
